language: c

script: printenv && uname -a && /bin/sh ./bin/setup.sh && ls -l m4 && cat configure && cd build && ../configure --enable-warnings && make && sudo make install && make test

notifications:
  recipients:
    - libslax-noise@googlegroups.com

branches:
  only:
    - master
    - develop
