blank_lines_lower_bound = 1
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
indent_style = "Visual"
max_width = 80
# merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
single_line_if_else_max_width = 70
space_before_fn_sig_paren = true
spaces_around_ranges = true
struct_lit_width = 80
use_field_init_shorthand  = true
wrap_comments = true
force_multiline_blocks = true
