.TH libslax 3 "21 July 2008"
.SH NAME
libslax \- library used to parse SLAX language stylesheets for libxslt
.SH DESCRIPTION
The 
.I libslax
library is used to parse SLAX transformations for 
.I libxslt.
This code is merged into
.I libxslt
and is built as part of that library, allowing easy access for SLAX
stylesheets.
.LP
.SH FILES
.TP 2.2i
.B /usr/lib/libslax_1.0.0/libslax.a
static library
.TP
.B /usr/lib/libslax_1.0.0/libslax.so
sharable library
.TP
.SH AUTHORS
Phil Shafer (phil@juniper.net).
.SH SEE ALSO
.IR libxslt (3), 
.IR libxml (3), 
.\" end of manual page
