/*
 * Copyright (c) 2016, Juniper Networks, Inc.
 * All rights reserved.
 * This SOFTWARE is licensed under the LICENSE provided in the
 * ../Copyright file. By downloading, installing, copying, or otherwise
 * using the SOFTWARE, you agree to be bound by the terms of that
 * LICENSE.
 *
 * Phil Shafer (phil@) June 2016
 *
 * We compile scripts into a set of rules, behaviors that are
 * triggered based on incoming elements.  These rules exist in their
 * own memory segment (pa_mmap_t) so they can be compiled once and
 * reused as needed.
 *
 * Rules are patterns to match and actions to execute when matched.
 * They are typically generated by compiling a script, but can be
 * generated directly.
 *
 * Rules are built in "states" (think YACC states) where a set of
 * rules
 */

#ifndef LIBSLAX_PIN_RULES_H
#define LIBSLAX_PIN_RULES_H

#include <parrotdb/pafixed.h>
#include <parrotdb/pabitmap.h>
#include <libpin/pin_node.h>
#include <libpin/pin_body.h>
#include <libpin/pin_exec.h>

typedef struct xo_filter_s xo_filter_t;

typedef uint8_t pin_action_type_t;

/* Values for pin_action_type_t */
#define PIA_NONE	0
#define PIA_DISCARD	1	/* Discard with all due haste */
#define PIA_SAVE	2	/* Save node (at insertion point) */
#define PIA_SAVE_ATSTR	3	/* Save node and attribute string */
#define PIA_SAVE_ATTRIB	4	/* Save node and parsed attributes */
#define PIA_EMIT	5	/* Emit as output */
#define PIA_RETURN	6	/* Force return from pin_parse() */
#define PIA_LITERAL	7	/* Emit a static literal node, discard matched element */
#define PIA_WRAP	8	/* Wrap matched element in a synthetic outer tag */
#define PIA_SAVE_ALL	9	/* Save node and entire subtree unconditionally */

/* Generated typed atoms for rule, state, and apply-entry ids */
#include "gen/pin_rule_id_gen.h"
#include "gen/pin_rstate_id_gen.h"
#include "gen/pin_apply_id_gen.h"

/*
 * A rule defines a behavior for an incoming token.  A token can be
 * copied, saved, or discarded.  Or a function callback can triggered.
 */
typedef struct pin_rule_s {
    pin_rule_id_t pr_next;	/* Next rule for this state */
    uint32_t pr_flags;		/* Flags for this rule */
    pa_bitmap_id_t pr_bitmap;	/* Elements affected by this rule */
    pin_action_type_t pr_action;	/* What to do when the rule matches */
    pin_name_id_t pr_mode;	/* Mode (namepool atom; null = default mode) */

    pin_rstate_id_t pr_child_state; /* Rulebook state for children */
    pin_op_id_t pr_close_ops;	/* Op sequence to run on CLOSE; null = use pr_action */
    pin_name_id_t pr_src_file;	/* Namepool atom: source XSLT filename (for debugging) */
    uint32_t pr_src_line;	/* Source line number (for debugging) */

    /* BIA_ (body instruction) fields: used by the streaming body executor */
    pin_name_id_t pr_use_tag;	/* For PIA_LITERAL: namepool atom of literal element name */
    pin_rstate_id_t pr_new_state;/* New state to enter on OPEN (for-each containers) */
    pin_name_id_t pr_literal_text; /* For PIA_LITERAL/PIA_WRAP: text of pre-emit literal content */
    pin_name_id_t pr_pre_tag;	/* For PIA_WRAP: pre-emit element name (before the wrap) */
    pin_body_instr_id_t pr_body; /* First body instruction; null = use pr_action */
    pin_body_retain_t pr_body_retain; /* Retention class for the matched element */
} pin_rule_t;

/* Flags for pr_flags */
#define PRF_MATCH_ALL	(1<<0)	/* Wildcard match */

/*
 * A state represents a set of associated rules
 */
typedef struct pin_rstate_s {
    pin_rule_id_t prbs_first_rule; /* Number of first rule (in xb_rules) */
    pin_rule_id_t prbs_default_rule; /* Number of default rule (in xb_rules) */
    uint16_t prbs_flags;	/* Flags for this state */
} pin_rstate_t;

/* Flags for prbs_flags */
#define PRBSF_INUSE	(1<<0)	/* State is used/defined */

typedef struct pin_rulebook_info_s {
    pin_rstate_id_t prsi_initial_state; /* First state in the rule book */
    pin_rstate_id_t prsi_max_state;     /* Maximum allocated (seen) state */
} pin_rulebook_info_t;

/*
 * One entry in the named-template registry.
 * Registered by pin_rulebook_named_add; looked up at runtime by PIN_OP_CALL.
 */
typedef struct pin_named_template_s {
    pin_name_id_t pnt_name;   /* template name atom */
    pin_op_id_t   pnt_ops;    /* first op in the body sequence */
} pin_named_template_t;

/*
 * One recorded xsl:call-template site, awaiting validation once the whole
 * compilation unit (all includes/imports) has finished compiling.  A name
 * that still doesn't resolve to a registered named template at that point
 * is a genuine error: a misspelled name, or a target that was rejected for
 * having an unsupported body.  Deferring the check this way means a call
 * to a template defined later in the document, or in an included/imported
 * file, is never mistaken for a missing one.
 */
typedef struct pin_pending_call_s {
    pin_name_id_t pc_name;      /* called template's name atom */
    pin_name_id_t pc_src_file;  /* source filename atom of the call site */
    uint32_t      pc_src_line;  /* source line number of the call site */
} pin_pending_call_t;

/*
 * One global variable or parameter binding.
 * Registered at compile time from top-level xsl:variable / xsl:param.
 * The value is a namepool atom for the string value; null atom = empty string.
 * For xsl:param the same slot is used; runtime override is not yet supported.
 */
typedef struct pin_global_var_s {
    pin_name_id_t pgv_name;   /* variable name atom */
    pin_name_id_t pgv_value;  /* string value atom (null = use pgv_expr) */
    pin_name_id_t pgv_expr;   /* raw select= expression (null = no expression) */
} pin_global_var_t;

/*
 * Settings from xsl:output.  Stored in the rulebook; read by the
 * emit functions to control XML declaration and indentation.
 */
typedef struct pin_output_settings_s {
    pin_name_id_t pos_method;           /* "xml", "html", "text" (null=xml) */
    pin_name_id_t pos_encoding;         /* e.g. "UTF-8" (null=UTF-8) */
    pin_name_id_t pos_doctype_public;
    pin_name_id_t pos_doctype_system;
    pin_name_id_t pos_media_type;
    unsigned      pos_omit_xml_decl : 1;     /* omit-xml-declaration="yes" */
    unsigned      pos_omit_xml_decl_set : 1; /* was omit-xml-declaration given? */
    unsigned      pos_indent : 1;            /* indent="yes" */
    unsigned      pos_indent_set : 1;        /* was indent= given? */
} pin_output_settings_t;

/*
 * Patricia-tree key for pin_apply_entry_t: (mode, name), mode leading.
 * Every entry is indexed by this key, not just default-mode ones; the
 * mode-scoped apply-templates dispatch in pin_parse.c looks entries up
 * directly by (apply_mode, name) instead of scanning the linked list.
 */
typedef struct pin_apply_key2_s {
    uint32_t pak_mode_be;   /* Mode atom (0 = default mode) */
    uint32_t pak_name_be;   /* Element name atom */
} pin_apply_key2_t;

/*
 * Builds the (mode, name) Patricia key used both by pin_rulebook_apply_add
 * (when inserting) and by pin_parse.c's apply-templates dispatch (when
 * looking a candidate up via pa_pat_get); the two must agree byte-for-byte.
 */
void pin_apply_key2_build (pin_apply_key2_t *key, pin_name_id_t mode_id,
			   pin_name_id_t name_id);

/*
 * One entry in the apply-templates dispatch patricia tree.
 * Keyed by pae_key2 (mode, name); see pin_apply_key2_t.
 */
typedef struct pin_apply_entry_s {
    pin_name_id_t  pae_name;         /* Element name atom */
    pin_name_id_t  pae_mode;         /* Mode atom (null = default mode) */
    pin_apply_key2_t pae_key2;       /* Patricia tree key: (pae_mode, pae_name) */
    pin_rule_id_t  pae_rule;         /* Rule to dispatch to via apply-templates */
    pin_apply_id_t pae_next;         /* Next entry in all-entries linked list */
    float          pae_priority;     /* Explicit or default priority (XSLT section 5.5) */
    int16_t        pae_import_prec;  /* 0 = main; -1,-2,... = imported depth */
} pin_apply_entry_t;

/* Fixed-point scale/clamp for folding a float priority into pmk_priority_inv_be */
#define PIN_PRI_SCALE	100.0	/* two decimal digits of precision */
#define PIN_PRI_MAX	300.0	/* clamp range: [-PIN_PRI_MAX, PIN_PRI_MAX] */

/*
 * Patricia-tree key for pin_mode_entry_t (prb_mode_pat).  Partitions
 * xsl:template match patterns by mode (the leading field, so ascending
 * pa_pat_find_next traversal visits all of one mode's entries together,
 * with the default mode's atom 0 sorting first) and, within a mode, orders
 * them by decreasing priority, then decreasing import precedence, then
 * insertion order -- the same order pin_compile_build_mode_filters replays
 * them into pin_filter_add_with_action, so its own last-wins tie-break
 * reproduces "later definition wins" on an exact priority/import_prec tie.
 * All fields are stored big-endian so ascending traversal order matches
 * the numeric order described above.
 */
typedef struct pin_mode_key_s {
    uint32_t pmk_mode_be;             /* Mode atom (0 = default mode) */
    uint16_t pmk_priority_inv_be;     /* UINT16_MAX - scaled/biased priority */
    uint16_t pmk_import_prec_inv_be;  /* UINT16_MAX - biased import_prec */
    uint32_t pmk_uniq_be;             /* Insertion-order uniquifier: final tiebreak */
} pin_mode_key_t;

/*
 * One xsl:template match pattern registered by pin_rulebook_mode_register,
 * awaiting batch-compilation into a mode-specific filter by
 * pin_compile_build_mode_filters.  pme_xpath_id interns the match= string
 * as a namepool atom at registration time: the caller (pin_compile_template)
 * frees its own copy right after registering, so a raw pointer would dangle.
 */
typedef struct pin_mode_entry_s {
    pin_mode_key_t pme_key;        /* Patricia tree key (see pin_mode_key_t) */
    pin_name_id_t  pme_mode;       /* Mode atom (0 = default mode) */
    pin_name_id_t  pme_xpath_id;   /* Namepool atom: xpath match pattern string */
    pin_rule_id_t  pme_rule;       /* Rule to fire when this pattern matches */
    float          pme_priority;   /* Explicit or default priority (XSLT section 5.5) */
    int16_t        pme_import_prec; /* 0 = main; -1,-2,... = imported depth */
} pin_mode_entry_t;

/*
 * One compiled filter for a non-default mode.  The default mode never
 * needs an entry here: it reuses the caller-supplied filter threaded
 * through pin_compile (see pin_compile_build_mode_filters and
 * pin_parse_current_filter).
 */
typedef struct pin_mode_filter_s {
    pin_name_id_t pmf_mode;    /* Mode atom this filter serves (never 0) */
    xo_filter_t  *pmf_xfp;     /* Compiled filter for this mode */
} pin_mode_filter_t;

/*
 * A rule set is an optimized set of rules
 */
typedef struct pin_rulebook_s {
    pin_workspace_t *prb_workspace; /* Our workspace */
    pin_parse_t *prb_script;	  /* Script we're loading/building */
    pin_rulebook_info_t *prb_infop; /* Our information the the pa_mmap_t */
    pa_fixed_t *prb_rules;	  /* List of rules (pin_rule_t) */
    pa_fixed_t *prb_states;	  /* List of states (pin_rule_state_t) */
    pa_fixed_t *prb_ops;	  /* Pool of op sequence nodes (pin_op_t) */
    pa_bitmap_t *prb_bitmaps;	  /* Pool of bitmaps */
    pa_fixed_t *prb_body_instrs;  /* Pool of body instructions (pin_body_instr_t) */
    pa_fixed_t *prb_apply_entries; /* Pool of apply-dispatch entries */
    pa_pat_t *prb_apply_pat;	  /* Patricia tree: (mode,name) key -> apply entry */
    pa_fixed_t *prb_mode_entries; /* Pool of mode-partition entries (pin_mode_entry_t) */
    pa_pat_t *prb_mode_pat;	  /* Patricia tree: pin_mode_key_t -> mode entry */
    uint32_t prb_mode_uniq;	  /* Next uniquifier for prb_mode_pat keys */
    pin_mode_filter_t *prb_mode_filters; /* Array of per-(non-default)-mode filters */
    uint32_t prb_mode_filters_len;
    uint32_t prb_mode_filters_cap;
    xo_filter_t **prb_if_filters; /* Per-BIA_IF compiled condition filters */
    uint32_t prb_if_filter_count; /* Number of entries in prb_if_filters */
    uint32_t prb_if_filter_size;   /* Allocated capacity of prb_if_filters */
    pin_rule_id_t prb_root_rule;  /* Rule for match="/" or a simple absolute
				     single-step path like match="/foo" (null
				     if none) */
    pin_name_id_t prb_root_name;  /* Expected root element name for
				     prb_root_rule; null means "any name"
				     (plain match="/") */
    pin_apply_id_t prb_apply_list; /* Head of all apply-entry linked list */
    pin_named_template_t *prb_named;      /* Array of named templates */
    uint32_t              prb_named_count;
    uint32_t              prb_named_size;
    pin_pending_call_t   *prb_pending_calls; /* call-template sites, pending validation */
    uint32_t              prb_pending_call_count;
    uint32_t              prb_pending_call_size;
    pin_global_var_t     *prb_globals;    /* Array of global variables/params */
    uint32_t              prb_global_count;
    uint32_t              prb_global_size;
    pin_output_settings_t prb_output;    /* Settings from xsl:output */
    unsigned              prb_strip_all : 1;    /* xsl:strip-space elements="*" (deep) */
    unsigned              prb_shallow_all : 1;  /* xsl:strip-space elements="*" shallow="yes" */
    pin_name_id_t        *prb_strip_names;       /* deep strip per-element list */
    uint32_t              prb_strip_name_count;
    uint32_t              prb_strip_name_size;
    pin_name_id_t        *prb_shallow_names;     /* shallow/exterior strip per-element list */
    uint32_t              prb_shallow_name_count;
    uint32_t              prb_shallow_name_size;
} pin_rulebook_t;

/* Values for the per-depth strip-mode stack (pin_parse_t::pp_strip_stack) */
#define PIN_STRIP_NONE    0  /* no whitespace stripping */
#define PIN_STRIP_SHALLOW 1  /* exterior: strip inter-element whitespace only */
#define PIN_STRIP_DEEP    2  /* full: strip all whitespace-only text nodes */

pin_rulebook_t *
pin_rulebook_open (const char *name);

pin_rulebook_t *
pin_rulebook_setup (pin_workspace_t *pwp, pin_parse_t *script, const char *name);

void
pin_rulebook_close (pin_rulebook_t *rules);

pin_rule_t *
pin_rulebook_find (pin_parse_t *parsep, pin_rulebook_t *prbp, pin_rstate_t *statep,
		  pin_name_id_t name_id, const char *pref, const char *name,
		  const char *attribs);

pin_rulebook_t *
pin_rulebook_prep (pin_parse_t *input, const char *name);

/*
 * Create a new rulebook state suitable for a for-each context:
 *   - One rule with 'select_name' in its bitmap -> select_action (e.g. SAVE)
 *   - A catch-all default rule -> default_action (e.g. DISCARD)
 * Returns the new state's id, or the null id on failure.
 * Uses the workspace namepool in prbp->prb_workspace for atom lookup.
 */
pin_rstate_id_t
pin_rulebook_add_foreach_state (pin_rulebook_t *prbp, const char *select_name,
				pin_action_type_t select_action,
				pin_action_type_t default_action);

/*
 * Create a foreach state where the selected element emits a static literal
 * node (PIA_LITERAL) with the given tag name and text content.
 */
pin_rstate_id_t
pin_rulebook_add_foreach_literal_state (pin_rulebook_t *prbp,
					const char *select_name,
					const char *literal_tag,
					const char *literal_text,
					pin_action_type_t default_action);

/*
 * Create a foreach state where the selected element is wrapped in a new
 * outer tag (PIA_WRAP).  The matched element is saved as a child of the
 * wrapper.  Optionally, a static pre-emit literal (<pre_tag>pre_text</pre_tag>)
 * is emitted before the wrapper for each matched element.
 */
pin_rstate_id_t
pin_rulebook_add_foreach_wrap_state (pin_rulebook_t *prbp,
				     const char *select_name,
				     const char *wrap_tag,
				     const char *pre_tag,
				     const char *pre_text,
				     pin_action_type_t default_action);

/*
 * Create a foreach state where the selected element is processed by a
 * compiled body instruction list.  body_head is the first instruction
 * (from pin_compile_body); retain describes how much of the matched
 * element must be buffered.
 */
pin_rstate_id_t
pin_rulebook_add_foreach_body_state (pin_rulebook_t *prbp,
				     const char *select_name,
				     pin_body_instr_id_t body_head,
				     pin_body_retain_t retain,
				     pin_action_type_t default_action);

/*
 * Add one (name, mode, rule) entry to the apply-templates patricia tree,
 * keyed by (mode, name); see pin_apply_key2_t.
 * name_id must already be interned in the workspace namepool.
 * Returns 0 on success, -1 on failure (e.g. tree not open, duplicate name).
 *
 * XXX Is this no longer needed?  pin_compile_template now registers every
 * template with pin_rulebook_mode_register instead, so the mode-scoped
 * apply-templates dispatch in pin_parse.c could look entries up directly
 * from prb_mode_pat rather than via this separate (mode,name) index.  Kept
 * for now because pin_parse.c's PBMODE_APPLY dispatch still calls it.
 */
int
pin_rulebook_apply_add (pin_rulebook_t *prbp,
			pin_name_id_t name_id, pin_name_id_t mode_id,
			pin_rule_id_t rid,
			float priority, int16_t import_prec);

/*
 * Register one xsl:template match pattern for later batch-compilation into
 * a mode-specific filter (see pin_compile_build_mode_filters in
 * pin_compile.c).  match_str is interned into the workspace namepool
 * immediately, so the caller's copy may be freed right after this call
 * returns.  Returns 0 on success, -1 on allocation failure.
 */
int
pin_rulebook_mode_register (pin_rulebook_t *prbp, pin_name_id_t mode_id,
			    const char *match_str, pin_rule_id_t rid,
			    float priority, int16_t import_prec);

/*
 * Iterate all registered mode-partition entries in key order (grouped by
 * mode, since mode is the leading key field; see pin_mode_key_t).  Pass
 * prev = NULL to get the first entry; pass a previously returned entry to
 * get the next one.  Returns NULL once iteration is exhausted.
 */
pin_mode_entry_t *
pin_rulebook_mode_next (pin_rulebook_t *prbp, pin_mode_entry_t *prev);

/*
 * Look up the compiled filter registered for a non-default mode, or NULL
 * if pin_rulebook_set_mode_filter has not been called for mode_id yet.
 */
xo_filter_t *
pin_rulebook_get_mode_filter (pin_rulebook_t *prbp, pin_name_id_t mode_id);

/*
 * Record the compiled filter for a non-default mode.  Called once per
 * mode by pin_compile_build_mode_filters; does not check for duplicates.
 * Returns 0 on success, -1 on allocation failure.
 */
int
pin_rulebook_set_mode_filter (pin_rulebook_t *prbp, pin_name_id_t mode_id,
			      xo_filter_t *xfp);

void
pin_rulebook_dump (pin_rulebook_t *prbp);

/*
 * Append a compiled per-BIA_IF condition filter to the rulebook's
 * prb_if_filters array.  Returns the index (for storage in bi_filter_idx),
 * or UINT32_MAX on allocation failure.
 */
uint32_t
pin_rulebook_if_filter_add (pin_rulebook_t *prbp, xo_filter_t *xfp);

/*
 * Register a named template (xsl:template name="...") with the rulebook.
 * name_id is the namepool atom for the template name; ops_id is the first
 * op of its compiled body.  Returns 0 on success, -1 on allocation failure.
 */
int
pin_rulebook_named_add (pin_rulebook_t *prbp, pin_name_id_t name_id,
                        pin_op_id_t ops_id);

/*
 * Look up a named template by name atom.
 * Returns the first op id of the template body, or the null id if not found.
 */
pin_op_id_t
pin_rulebook_named_find (pin_rulebook_t *prbp, pin_name_id_t name_id);

/*
 * Report whether a named template is registered, regardless of whether its
 * body compiled to a non-null op sequence.  pin_rulebook_named_find cannot
 * make this distinction on its own: a template with a legitimately empty
 * body registers with a null op id, which looks identical to "not found".
 * Callers that need to tell those two cases apart (e.g. validating
 * xsl:call-template targets) use this instead.
 */
int
pin_rulebook_named_exists (pin_rulebook_t *prbp, pin_name_id_t name_id);

/*
 * Record one xsl:call-template site for later validation, once the whole
 * compilation unit has finished compiling.  See pin_pending_call_t.
 * Returns 0 on success, -1 on allocation failure.
 */
int
pin_rulebook_pending_call_add (pin_rulebook_t *prbp, pin_name_id_t name_id,
			       pin_name_id_t src_file, uint32_t src_line);

/*
 * Register a global variable or parameter.
 * value_id is the namepool atom for the string value (null atom = empty).
 * If a binding for name_id already exists it is overwritten.
 * Returns 0 on success, -1 on allocation failure.
 */
int
pin_rulebook_global_add (pin_rulebook_t *prbp,
                         pin_name_id_t name_id, pin_name_id_t value_id);

/*
 * Look up a global variable by name atom.
 * Returns the value namepool atom, or the null atom if not found or
 * if the variable has only a deferred expression (pgv_expr is set).
 * Note: the null atom is also a valid value (empty string), so use
 * pin_rulebook_global_defined() when you need to distinguish the two.
 */
pin_name_id_t
pin_rulebook_global_find (pin_rulebook_t *prbp, pin_name_id_t name_id);

/*
 * Register an expression-valued global: the select= text is stored in
 * pgv_expr and evaluated lazily at load time.  Used when the expression
 * cannot be resolved to a static string at compile time (e.g. "$other").
 * If the entry already has an explicit pgv_value (set by pin_rulebook_global_add)
 * the expression is ignored -- the explicit value takes priority.
 */
int
pin_rulebook_global_set_expr (pin_rulebook_t *prbp,
                               pin_name_id_t name_id, pin_name_id_t expr_id);

/*
 * Return the pgv_expr atom for name_id, or the null atom if none.
 */
pin_name_id_t
pin_rulebook_global_expr_find (pin_rulebook_t *prbp, pin_name_id_t name_id);

/*
 * Return non-zero if a global variable or parameter with name_id is
 * registered in prbp, regardless of its value.
 */
int
pin_rulebook_global_defined (pin_rulebook_t *prbp, pin_name_id_t name_id);

/*
 * Add name_id to the deep (shallow=0) or shallow/exterior (shallow=1)
 * strip-space element list.  Duplicates are silently ignored.
 * Returns 0 on success, -1 on allocation failure.
 */
int
pin_rulebook_strip_name_add (pin_rulebook_t *prbp,
                              pin_name_id_t name_id, int shallow);

/*
 * Return the strip mode (PIN_STRIP_*) for name_id given the rulebook's
 * strip-space directives.  Per-element entries take precedence over the
 * elements="*" wildcards; deep takes precedence over shallow.
 */
uint8_t
pin_rulebook_strip_mode (pin_rulebook_t *prbp, pin_name_id_t name_id);

#include "gen/pin_rule_id_funcs_gen.h"
#include "gen/pin_rstate_id_funcs_gen.h"
#include "gen/pin_body_instr_id_funcs_gen.h"
#include "gen/pin_apply_id_funcs_gen.h"
#include "gen/pin_op_id_funcs_gen.h"

/* Aliases: pin_rulebook_rule(prbp, rid) and pin_rulebook_state(prbp, sid) */
#define pin_rulebook_rule	pin_rule_addr
#define pin_rulebook_state(_xrbp, _sid) pin_rstate_addr((_xrbp), (_sid))

#endif /* LIBSLAX_PIN_RULES_H */
