/*
 * Copyright (c) 2016, Juniper Networks, Inc.
 * All rights reserved.
 * This SOFTWARE is licensed under the LICENSE provided in the
 * ../Copyright file. By downloading, installing, copying, or otherwise
 * using the SOFTWARE, you agree to be bound by the terms of that
 * LICENSE.
 *
 * Phil Shafer (phil@) June 2016
 *
 * We compile scripts into a set of rules, behaviors that are
 * triggered based on incoming elements.  These rules exist in their
 * own memory segment (pa_mmap_t) so they can be compiled once and
 * reused as needed.
 *
 * Rules are patterns to match and actions to execute when matched.
 * They are typically generated by compiling a script, but can be
 * generated directly.
 *
 * Rules are built in "states" (think YACC states) where a set of
 * rules
 */

#ifndef LIBSLAX_PIN_RULES_H
#define LIBSLAX_PIN_RULES_H

#include <parrotdb/pafixed.h>
#include <parrotdb/pabitmap.h>
#include <libpin/pin_node.h>
#include <libpin/pin_body.h>

typedef uint8_t pin_action_type_t;

/* Values for pin_action_type_t */
#define PIA_NONE	0
#define PIA_DISCARD	1	/* Discard with all due haste */
#define PIA_SAVE	2	/* Save node (at insertion point) */
#define PIA_SAVE_ATSTR	3	/* Save node and attribute string */
#define PIA_SAVE_ATTRIB	4	/* Save node and parsed attributes */
#define PIA_EMIT	5	/* Emit as output */
#define PIA_RETURN	6	/* Force return from pin_parse() */
#define PIA_LITERAL	7	/* Emit a static literal node, discard matched element */
#define PIA_WRAP	8	/* Wrap matched element in a synthetic outer tag */

/* Generated typed atoms for rule and state ids (wraps pa_fixed_atom_t) */
#include "gen/pin_rule_id_gen.h"
#include "gen/pin_rstate_id_gen.h"

/*
 * A rule defines a behavior for an incoming token.  A token can be
 * copied, saved, or discarded.  Or a function callback can triggered.
 */
typedef struct pin_rule_s {
    pin_rule_id_t pr_next;	/* Next rule for this state */
    uint32_t pr_flags;		/* Flags for this rule */
    pa_bitmap_id_t pr_bitmap;	/* Elements affected by this rule */
    pin_action_type_t pr_action;	/* What to do when the rule matches */
    pin_name_id_t pr_mode;	/* Mode (namepool atom; null = default mode) */
    pin_name_id_t pr_use_tag;	/* For PIA_LITERAL: namepool atom of literal element name */
    pin_rstate_id_t pr_new_state;/* New state (in the rulebook) to enter */
    pin_name_id_t pr_literal_text; /* For PIA_LITERAL/PIA_WRAP: text of pre-emit literal content */
    pin_name_id_t pr_pre_tag;	/* For PIA_WRAP: pre-emit element name (before the wrap) */
    pin_body_instr_id_t pr_body; /* First body instruction; null = use pr_action */
    pin_body_retain_t pr_body_retain; /* Retention class for the matched element */
} pin_rule_t;

/* Flags for pr_flags */
#define PRF_MATCH_ALL	(1<<0)	/* Wildcard match */

/*
 * A state represents a set of associated rules
 */
typedef struct pin_rstate_s {
    pin_rule_id_t prbs_first_rule; /* Number of first rule (in xb_rules) */
    pin_rule_id_t prbs_default_rule; /* Number of default rule (in xb_rules) */
    uint16_t prbs_flags;	/* Flags for this state */
} pin_rstate_t;

/* Flags for prbs_flags */
#define PRBSF_INUSE	(1<<0)	/* State is used/defined */

typedef struct pin_rulebook_info_s {
    pin_rstate_id_t prsi_initial_state; /* First state in the rule book */
    pin_rstate_id_t prsi_max_state;     /* Maximum allocated (seen) state */
} pin_rulebook_info_t;

/*
 * A rule set is an optimized set of rules
 */
typedef struct pin_rulebook_s {
    pin_workspace_t *prb_workspace; /* Our workspace */
    pin_parse_t *prb_script;	  /* Script we're loading/building */
    pin_rulebook_info_t *prb_infop; /* Our information the the pa_mmap_t */
    pa_fixed_t *prb_rules;	  /* List of rules (pin_rule_t) */
    pa_fixed_t *prb_states;	  /* List of states (pin_rule_state_t) */
    pa_bitmap_t *prb_bitmaps;	  /* Pool of bitmaps */
    pa_fixed_t *prb_body_instrs;  /* Pool of body instructions (pin_body_instr_t) */
} pin_rulebook_t;

pin_rulebook_t *
pin_rulebook_open (const char *name);

pin_rulebook_t *
pin_rulebook_setup (pin_workspace_t *pwp, pin_parse_t *script, const char *name);

void
pin_rulebook_close (pin_rulebook_t *rules);

pin_rule_t *
pin_rulebook_find (pin_parse_t *parsep, pin_rulebook_t *prbp, pin_rstate_t *statep,
		  pin_name_id_t name_id, const char *pref, const char *name,
		  const char *attribs);

pin_rulebook_t *
pin_rulebook_prep (pin_parse_t *input, const char *name);

/*
 * Create a new rulebook state suitable for a for-each context:
 *   - One rule with 'select_name' in its bitmap → select_action (e.g. SAVE)
 *   - A catch-all default rule → default_action (e.g. DISCARD)
 * Returns the new state's id, or the null id on failure.
 * Uses the workspace namepool in prbp->prb_workspace for atom lookup.
 */
pin_rstate_id_t
pin_rulebook_add_foreach_state (pin_rulebook_t *prbp, const char *select_name,
				pin_action_type_t select_action,
				pin_action_type_t default_action);

/*
 * Create a foreach state where the selected element emits a static literal
 * node (PIA_LITERAL) with the given tag name and text content.
 */
pin_rstate_id_t
pin_rulebook_add_foreach_literal_state (pin_rulebook_t *prbp,
					const char *select_name,
					const char *literal_tag,
					const char *literal_text,
					pin_action_type_t default_action);

/*
 * Create a foreach state where the selected element is wrapped in a new
 * outer tag (PIA_WRAP).  The matched element is saved as a child of the
 * wrapper.  Optionally, a static pre-emit literal (<pre_tag>pre_text</pre_tag>)
 * is emitted before the wrapper for each matched element.
 */
pin_rstate_id_t
pin_rulebook_add_foreach_wrap_state (pin_rulebook_t *prbp,
				     const char *select_name,
				     const char *wrap_tag,
				     const char *pre_tag,
				     const char *pre_text,
				     pin_action_type_t default_action);

/*
 * Create a foreach state where the selected element is processed by a
 * compiled body instruction list.  body_head is the first instruction
 * (from pin_slax_compile_body); retain describes how much of the matched
 * element must be buffered.
 */
pin_rstate_id_t
pin_rulebook_add_foreach_body_state (pin_rulebook_t *prbp,
				     const char *select_name,
				     pin_body_instr_id_t body_head,
				     pin_body_retain_t retain,
				     pin_action_type_t default_action);

void
pin_rulebook_dump (pin_rulebook_t *prbp);

#include "gen/pin_rule_id_funcs_gen.h"
#include "gen/pin_rstate_id_funcs_gen.h"
#include "gen/pin_body_instr_id_funcs_gen.h"

/* Aliases: pin_rulebook_rule(prbp, rid) and pin_rulebook_state(prbp, sid) */
#define pin_rulebook_rule	pin_rule_addr
#define pin_rulebook_state(_xrbp, _sid) pin_rstate_addr((_xrbp), (_sid))

#endif /* LIBSLAX_PIN_RULES_H */
