+/* Machine Crafted with Care (tm) by slaxWriter */
 version 1.0;
 
 match / {
     var $location = location;
-
     <top> {
-	<element attr1="one" attr2="two">;
-
-	<location state=$location/state
-              zip=$location/zip5 _ "-" _ $location/zip4>;
-
-	<avt sign="{here}">;
+        <element attr1 = "one" attr2 = "two">;
+        <location state = $location/state zip = $location/zip5 _ "-" _ $location/zip4>;
+        <avt sign = "{here}">;
     }
 }
+
