+/* Machine Crafted with Care (tm) by slaxWriter */
 version 1.0;
 
-<xsl:output method="xml" indent="yes" media-type="image/svg">;
+<xsl:output method = "xml" indent = "yes" media-type = "image/svg">;
 
 match * {
+    
     for-each (configuration/interfaces/unit) {
-	<xsl:sort some-obnoxious-option="some-obnoxious-value">;
+        <xsl:sort some-obnoxious-option = "some-obnoxious-value">;
     }
 }
+
