+/* Machine Crafted with Care (tm) by slaxWriter */
 version 1.0;
 
 match / {
@@ -5,9 +6,7 @@
         <one> "test";
         <two> "The answer is " _ results/answer _ ".";
         <three> results/count _ " attempts made by " _ results/user;
-        <four> {
-            expr results/count _ " attempts made by " _ results/user;
-        }
+        <four> results/count _ " attempts made by " _ results/user;
         <five> {
             expr results/count;
             expr " attempts made by ";
@@ -16,3 +15,4 @@
         <six> results/message;
     }
 }
+
