+/* Machine Crafted with Care (tm) by slaxWriter */
 version 1.0;
 
 ns foo exclude = "http://example.com/foo";
 ns jcs extension = "http://xml.juniper.net/jcs";
-
 ns a = "http://example.com/1";
 ns "http://example.com/global";
 ns b = "http://example.com/2";
 
 match / {
     ns c = "http://example.com/3";
+    
     <top> {
 	ns a = "http://example.com/4";
+        
 	apply-templates commit-script-input/configuration;
     }
 }
+
